name: 'Setup project'
description: 'Install Node.js, dependencies'

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.20'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install
      shell: bash
