name: Run Prettier check

on:
  workflow_call:
  workflow_dispatch:

jobs:
  run-prettier-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up project
        uses: ./.github/actions/setup-project

      - name: Run Prettier check
        run: yarn prettier --check .
